# Generated by Django 5.0.4 on 2024-04-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('shopname', models.CharField(max_length=50, verbose_name='店铺名称')),
                ('shopaddress', models.CharField(max_length=50, verbose_name='店铺地址')),
                ('username', models.CharField(max_length=50, verbose_name='用户名称')),
                ('useraddresss', models.CharField(max_length=50, verbose_name='用户地址')),
                ('delivername', models.CharField(max_length=50, verbose_name='配送员姓名')),
                ('foodprice', models.FloatField(verbose_name='价格')),
                ('deliverprice', models.FloatField(verbose_name='配送费')),
            ],
        ),
    ]
