# Generated by Django 5.0.4 on 2024-04-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待配送'), (2, '已配送')], default=1, verbose_name='状态'),
        ),
    ]
