# Generated by Django 5.0.4 on 2024-04-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='delivername',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='deliverprice',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='foodname',
            field=models.CharField(default=0, max_length=50, verbose_name='菜品名称'),
            preserve_default=False,
        ),
    ]
