# Generated by Django 5.0.4 on 2024-04-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderinfo_delivername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='amounts',
            field=models.FloatField(default=0, verbose_name='数量'),
            preserve_default=False,
        ),
    ]
