# Generated by Django 5.0.4 on 2024-04-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderinfo_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='amounts',
            field=models.IntegerField(verbose_name='数量'),
        ),
    ]
