# Generated by Django 5.0.4 on 2024-04-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderinfo_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='totalmoney',
            field=models.FloatField(default=0, verbose_name='总价'),
            preserve_default=False,
        ),
    ]
