# Generated by Django 5.0.4 on 2024-04-17 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_foodinfo_foodid'),
        ('orders', '0006_orderinfo_totalmoney'),
        ('userprofile', '0009_alter_adminiinfo_adminid_alter_userinfo_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='foodId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.foodinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userinfo'),
            preserve_default=False,
        ),
    ]
