# Generated by Django 5.0.4 on 2024-04-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_delete_adminiinfo_delete_deliverinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminiInfo',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='deliverInfo',
            fields=[
                ('deliverid', models.AutoField(primary_key=True, serialize=False)),
                ('delivername', models.CharField(max_length=16, verbose_name='姓名')),
                ('deliverprice', models.FloatField(verbose_name='配送费')),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('userphone', models.CharField(max_length=16, verbose_name='电话')),
                ('useraddress', models.CharField(max_length=16, verbose_name='地址')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('money', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='余额')),
            ],
        ),
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodinfo', verbose_name='菜品编号')),
            ],
        ),
    ]
