# Generated by Django 5.0.4 on 2024-04-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='deliverinfo',
            name='password',
            field=models.CharField(default=1, max_length=16, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='orderInfo',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
