# Generated by Django 5.0.4 on 2024-04-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_profile_user_deliverinfo_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deliverInfo',
        ),
    ]
