# Generated by Django 5.0.4 on 2024-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='money',
            field=models.FloatField(default=100, verbose_name='余额'),
        ),
    ]
