# Generated by Django 5.0.4 on 2024-04-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_userinfo_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='useraddress',
            field=models.CharField(max_length=50, verbose_name='地址'),
        ),
    ]
