# Generated by Django 5.0.4 on 2024-04-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_userinfo_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminiinfo',
            name='adminId',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
