# Generated by Django 5.0.4 on 2024-04-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminiInfo',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='shopInfo',
            fields=[
                ('shopid', models.AutoField(primary_key=True, serialize=False)),
                ('shopname', models.CharField(max_length=16, verbose_name='店铺名称')),
                ('shopphone', models.CharField(max_length=16, verbose_name='电话')),
                ('shopaddress', models.CharField(max_length=16, verbose_name='地址')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('worktime', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('userphone', models.CharField(max_length=16, verbose_name='电话')),
                ('useraddress', models.CharField(max_length=16, verbose_name='地址')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
    ]
