# Generated by Django 5.0.4 on 2024-04-14 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverInfo',
            fields=[
                ('deliverid', models.AutoField(primary_key=True, serialize=False)),
                ('delivername', models.CharField(max_length=16, verbose_name='姓名')),
                ('deliverprice', models.FloatField(verbose_name='配送费')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='money',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='余额'),
        ),
        migrations.CreateModel(
            name='foodInfo',
            fields=[
                ('foodid', models.AutoField(primary_key=True, serialize=False)),
                ('foodprice', models.FloatField(verbose_name='价格')),
                ('foodname', models.CharField(max_length=20, verbose_name='名称')),
                ('describ', models.TextField(verbose_name='菜品描述')),
                ('belongshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shopinfo')),
            ],
        ),
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodinfo', verbose_name='菜品编号')),
            ],
        ),
    ]
