# Generated by Django 5.0.4 on 2024-04-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_deliverinfo_userinfo_money_foodinfo_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='getmoney',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='营业额'),
        ),
    ]
