# Generated by Django 5.0.4 on 2024-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shopinfo_getmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinfo',
            name='tupian',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
