# Generated by Django 5.0.4 on 2024-04-15 16:22

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_adminiinfo_delete_deliverinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinfo',
            name='tupian',
            field=imagekit.models.fields.ProcessedImageField(upload_to='food/%Y%m%d'),
        ),
    ]
