# Generated by Django 5.0.4 on 2024-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_foodinfo_tupian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinfo',
            name='foodname',
            field=models.CharField(max_length=20, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='shopname',
            field=models.CharField(max_length=16, unique=True, verbose_name='店铺名称'),
        ),
    ]
