# Generated by Django 5.0.4 on 2024-04-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_foodinfo_foodname_alter_shopinfo_shopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='getmoney',
            field=models.FloatField(default=100, verbose_name='营业额'),
        ),
    ]
