# Generated by Django 5.0.4 on 2024-04-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_shopinfo_getmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinfo',
            name='foodid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
