# Generated by Django 5.0.4 on 2024-04-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='commentfood',
            field=models.CharField(max_length=20, verbose_name='菜品名称'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='commentuser',
            field=models.CharField(max_length=20, verbose_name='用户名称'),
        ),
    ]
