# Generated by Django 5.0.4 on 2024-04-17 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_foodinfo_foodid'),
        ('comments', '0002_alter_commentinfo_commentfood_and_more'),
        ('userprofile', '0009_alter_adminiinfo_adminid_alter_userinfo_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentinfo',
            name='commentfoodid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.foodinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='commentuserid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userinfo'),
            preserve_default=False,
        ),
    ]
